package io.ethers.abi.error

import io.ethers.abi.error.CustomErrorRegistry.appendResolver
import io.ethers.abi.error.CustomErrorRegistry.prependResolver
import io.ethers.core.Result
import io.ethers.core.failure
import io.ethers.core.success
import io.ethers.core.types.Bytes

/**
 * Registry of custom contract errors. This registry is used to decode errors returned by contract calls. By default,
 * it contains [CustomErrorFactoryResolver] which can decode errors generated by the ABI generator.
 *
 * Custom resolvers can be added by calling [prependResolver] or [appendResolver]. The resolvers are called in order,
 * and the first resolver that can decode the error is used.
 * */
object CustomErrorRegistry {
    private val resolvers = ArrayList<CustomErrorResolver>().apply {
        add(CustomErrorFactoryResolver)
    }

    /**
     * Add [CustomErrorResolver] to the beginning of the list of resolvers.
     * */
    @JvmStatic
    fun prependResolver(resolver: CustomErrorResolver) {
        synchronized(resolvers) {
            resolvers.add(0, resolver)
        }
    }

    /**
     * Add [CustomErrorResolver] to the end of the list of resolvers.
     * */
    @JvmStatic
    fun appendResolver(resolver: CustomErrorResolver) {
        synchronized(resolvers) {
            resolvers.add(resolver)
        }
    }

    /**
     * Return decoded [CustomContractError] from the first [CustomErrorResolver] that can decode it. If no resolver can decode
     * the error, return null.
     *
     * @return the decoded [CustomContractError], or null if no resolver can decode it.
     * */
    @JvmStatic
    fun getOrNull(error: Bytes): CustomContractError? {
        if (error.size < 4) return null

        for (i in resolvers.indices) {
            val customError = try {
                resolvers[i].resolve(error)
            } catch (_: Exception) {
                return null
            }
            if (customError != null) return customError
        }

        return null
    }

    /**
     * Try to return decoded [CustomContractError] from the first [CustomErrorResolver] that can decode it.
     *
     * @return the decoded [CustomContractError], or a [ContractErrorDecodingError] if decoding fails.
     * */
    @JvmStatic
    fun tryGet(error: Bytes): Result<CustomContractError, ContractErrorDecodingError> {
        if (error.size < 4) return failure(ContractErrorDecodingError.NoMatchingError(error, emptyList()))

        for (i in resolvers.indices) {
            when (val customError = resolvers[i].tryResolve(error)) {
                is Result.Success -> return success(customError.value)
                is Result.Failure -> {
                    if (customError.error !is ContractErrorDecodingError.NoMatchingError) {
                        return failure(customError.error)
                    }
                }
            }
        }

        return failure(ContractErrorDecodingError.NoMatchingError(error, emptyList()))
    }
}

/**
 * Resolver for decoding [CustomContractError] from [Bytes].
 * */
interface CustomErrorResolver {
    fun resolve(error: Bytes): CustomContractError?

    fun tryResolve(error: Bytes): Result<CustomContractError, ContractErrorDecodingError> {
        return try {
            resolve(error)?.let(::success)
                ?: failure(ContractErrorDecodingError.NoMatchingError(error, emptyList()))
        } catch (e: Exception) {
            failure(ContractErrorDecodingError.MalformedError(error, null, e))
        }
    }
}

/**
 * [CustomErrorResolver] that uses a list of [CustomErrorFactory] to decode [CustomContractError]s. ABI generated contract
 * errors are automatically added to this resolver.
 * */
object CustomErrorFactoryResolver : CustomErrorResolver {
    private val factories = ArrayList<CustomErrorFactory<*>>()

    @JvmStatic
    fun <T : CustomContractError> addFactories(newFactories: Array<CustomErrorFactory<out T>>) {
        synchronized(factories) {
            factories.addAll(newFactories)
        }
    }

    @JvmStatic
    fun <T : CustomContractError> addFactories(newFactories: List<CustomErrorFactory<out T>>) {
        synchronized(factories) {
            factories.addAll(newFactories)
        }
    }

    override fun resolve(error: Bytes): CustomContractError? {
        // the values are only appended to the end of the list, so we can safely iterate by index. Worst case,
        // we miss newly added errors in the current iteration.
        for (i in factories.indices) {
            val factory = factories[i]
            if (error.size < 4) return null
            if (!error.startsWith(factory.abi.selector)) continue
            return factory.decodeOrNull(error)
        }

        return null
    }

    override fun tryResolve(error: Bytes): Result<CustomContractError, ContractErrorDecodingError> {
        // the values are only appended to the end of the list, so we can safely iterate by index. Worst case,
        // we miss newly added errors in the current iteration.
        for (i in factories.indices) {
            when (val decoded = factories[i].tryDecode(error)) {
                is Result.Success -> return success(decoded.value)
                is Result.Failure -> {
                    if (decoded.error !is ContractErrorDecodingError.NoMatchingError) {
                        return failure(decoded.error)
                    }
                }
            }
        }

        return failure(ContractErrorDecodingError.NoMatchingError(error, factories.map { it.abi }))
    }
}
