package io.ethers.abi.error

import io.ethers.abi.AbiFunction
import io.ethers.abi.error.CustomErrorRegistry.appendResolver
import io.ethers.abi.error.CustomErrorRegistry.prependResolver
import io.ethers.core.Result
import io.ethers.core.failure
import io.ethers.core.success
import io.ethers.core.types.Bytes
import kotlinx.atomicfu.locks.SynchronizedObject
import kotlinx.atomicfu.locks.synchronized
import kotlin.jvm.JvmStatic

/**
 * Registry of custom contract errors. This registry is used to decode errors returned by contract calls. By default,
 * it contains [CustomErrorFactoryResolver] which can decode errors generated by the ABI generator.
 *
 * Custom resolvers can be added by calling [prependResolver] or [appendResolver]. The resolvers are called in order,
 * and the first resolver that can decode the error is used.
 * */
object CustomErrorRegistry {
    // `kotlin.synchronized` is JVM-only, so writes are guarded by an atomicfu lock instead. On the JVM this still
    // compiles down to a monitor, so behaviour is unchanged.
    private val lock = SynchronizedObject()

    private val resolvers = ArrayList<CustomErrorResolver>().apply {
        add(CustomErrorFactoryResolver)
    }

    /**
     * Add [CustomErrorResolver] to the beginning of the list of resolvers.
     * */
    @JvmStatic
    fun prependResolver(resolver: CustomErrorResolver) {
        synchronized(lock) {
            resolvers.add(0, resolver)
        }
    }

    /**
     * Add [CustomErrorResolver] to the end of the list of resolvers.
     * */
    @JvmStatic
    fun appendResolver(resolver: CustomErrorResolver) {
        synchronized(lock) {
            resolvers.add(resolver)
        }
    }

    /**
     * Return decoded [CustomContractError] from the first [CustomErrorResolver] that can decode it. If no resolver can decode
     * the error, return null.
     *
     * @return the decoded [CustomContractError], or null if no resolver can decode it.
     * */
    @JvmStatic
    fun getOrNull(error: Bytes): CustomContractError? {
        if (error.size < 4) return null

        for (i in resolvers.indices) {
            val customError = try {
                resolvers[i].resolveOrNull(error)
            } catch (_: Exception) {
                return null
            }
            if (customError != null) return customError
        }

        return null
    }

    /**
     * Try to return decoded [CustomContractError] from the first [CustomErrorResolver] that can decode it.
     *
     * @return the decoded [CustomContractError], or a [ContractErrorDecodingError] if decoding fails.
     * */
    @JvmStatic
    fun tryGet(error: Bytes): Result<CustomContractError, ContractErrorDecodingError> {
        if (error.size < 4) return failure(ContractErrorDecodingError.NoMatchingError(error, emptyList()))

        // collected from each resolver, so the returned NoMatchingError names everything that was tried
        val expectedErrors = ArrayList<AbiFunction>()

        for (i in resolvers.indices) {
            when (val customError = resolvers[i].tryResolve(error)) {
                is Result.Success -> return success(customError.value)
                is Result.Failure -> {
                    val err = customError.error
                    if (err !is ContractErrorDecodingError.NoMatchingError) return failure(err)
                    expectedErrors.addAll(err.expectedErrors)
                }
            }
        }

        return failure(ContractErrorDecodingError.NoMatchingError(error, expectedErrors))
    }
}

/**
 * Resolver for decoding [CustomContractError] from [Bytes].
 * */
interface CustomErrorResolver {
    /**
     * Decode [error] into a [CustomContractError], returning null if this resolver cannot decode it.
     *
     * If you need to know why decoding failed, use [tryResolve].
     * */
    fun resolveOrNull(error: Bytes): CustomContractError?

    fun tryResolve(error: Bytes): Result<CustomContractError, ContractErrorDecodingError> {
        return try {
            resolveOrNull(error)?.let(::success)
                ?: failure(ContractErrorDecodingError.NoMatchingError(error, emptyList()))
        } catch (e: Exception) {
            failure(ContractErrorDecodingError.MalformedError(error, null, e))
        }
    }
}

/**
 * [CustomErrorResolver] that uses a list of [CustomErrorFactory] to decode [CustomContractError]s. ABI generated contract
 * errors are automatically added to this resolver.
 * */
object CustomErrorFactoryResolver : CustomErrorResolver {
    private val lock = SynchronizedObject()

    private val factories = ArrayList<CustomErrorFactory<*>>()

    @JvmStatic
    fun <T : CustomContractError> addFactories(newFactories: Array<CustomErrorFactory<out T>>) {
        synchronized(lock) {
            factories.addAll(newFactories)
        }
    }

    @JvmStatic
    fun <T : CustomContractError> addFactories(newFactories: List<CustomErrorFactory<out T>>) {
        synchronized(lock) {
            factories.addAll(newFactories)
        }
    }

    override fun resolveOrNull(error: Bytes): CustomContractError? {
        if (error.size < 4) return null

        // the values are only appended to the end of the list, so we can safely iterate by index. Worst case,
        // we miss newly added errors in the current iteration.
        for (i in factories.indices) {
            // keep going on a decoding failure: distinct errors can share a 4-byte selector
            return factories[i].decodeOrNull(error) ?: continue
        }

        return null
    }

    override fun tryResolve(error: Bytes): Result<CustomContractError, ContractErrorDecodingError> {
        // the values are only appended to the end of the list, so we can safely iterate by index. Worst case,
        // we miss newly added errors in the current iteration.
        for (i in factories.indices) {
            when (val decoded = factories[i].tryDecode(error)) {
                is Result.Success -> return success(decoded.value)
                is Result.Failure -> {
                    if (decoded.error !is ContractErrorDecodingError.NoMatchingError) {
                        return failure(decoded.error)
                    }
                }
            }
        }

        return failure(ContractErrorDecodingError.NoMatchingError(error, factories.map { it.abi }))
    }
}
