package io.ethers.abigen

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.File
import java.util.Collections
import java.util.concurrent.ConcurrentHashMap

/**
 * Builder for a custom error loader class, which is used to force the loading of all classes added
 * via [addContract] function. The generated class has a dummy "load()" function which is called
 * to force-load the loader class, which in turn forces the loading of all added contracts.
 * */
class ErrorLoaderBuilder(
    loaderNamePrefix: String,
    private val destination: File,
) {
    private val contracts = Collections.synchronizedList(ArrayList<ClassName>())
    private val className = ClassName(PACKAGE_NAME, loaderName(loaderNamePrefix))

    val canonicalName: String
        get() = className.canonicalName

    fun addContract(contractCanonicalName: String) {
        val segments = contractCanonicalName.split('.')
        val pkg = if (segments.size <= 1) "" else segments.subList(0, segments.size - 1).joinToString(".")
        val clazz = segments.last()

        contracts.add(ClassName(pkg, clazz))
    }

    fun build() {
        val fileBuilder = FileSpec.builder(className)
            .indent("    ") // 1 tab / 4 spaces

        val loaderBuilder = TypeSpec.objectBuilder(className)
        loaderBuilder.addKdoc(
            """
            Custom error loader class which forces the loading of all contracts added via [addContract] function. 
            
            Makes it possible to auto-register all custom errors via [io.ethers.abi.error.CustomErrorRegistry] on
            first access to any auto-generated contract.
            
            This class is generated by [io.ethers.abigen.ErrorLoaderBuilder].
            """.trimIndent(),
        )

        val companions = contracts.map { it.nestedClass("Companion") }
        loaderBuilder.addProperty(
            PropertySpec
                .builder("contracts", List::class.parameterizedBy(Any::class))
                .addModifiers(KModifier.PRIVATE)
                .initializer(companions.joinToString(prefix = "listOf(", postfix = ")"))
                .build(),
        )

        loaderBuilder.addFunction(
            FunSpec.builder("load")
                .addModifiers(KModifier.PUBLIC)
                .addComment("Dummy function to force the class to be loaded")
                .build(),
        )

        fileBuilder.addType(loaderBuilder.build())
        fileBuilder.build().writeTo(destination)
    }

    companion object {
        private const val PACKAGE_NAME = "io.ethers.abigen.loaders"
        private const val BASE_NAME = "AbigenCustomErrorLoader"
        private val NAME_DEDUPLICATION = ConcurrentHashMap<String, Int>()

        /**
         * Get deduplicated loader name. Duplicate names can get generated if there are multiple abigen gradle tasks
         * in the same module.
         * */
        private fun loaderName(prefix: String): String {
            val count = NAME_DEDUPLICATION.merge(prefix, 1) { a, b -> a + b }!!
            if (count == 1) {
                return "$prefix$BASE_NAME"
            }
            return "$prefix$BASE_NAME${count.dec()}"
        }
    }
}
